package PART_D;

import adt.LList;
import adt.ListInterface;
import entity.Attendance;
import entity.employee;
import fooddeliverysystem.MainForm;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jiaweiloo
 */
public class employeeInt extends javax.swing.JFrame {

    MainForm mainform;
    ListInterface<employee> empList ;
    ListInterface<Attendance> attdList ;
    /**
     * Creates new form employeeInt
     */
    public employeeInt() {
        initComponents();
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        attdTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLogout.setText("Logout");

        attdTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Clockin", "Clockout", "lunch_clockout", "lunch_clockin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(attdTable);
        if (attdTable.getColumnModel().getColumnCount() > 0) {
            attdTable.getColumnModel().getColumn(0).setHeaderValue("ID");
            attdTable.getColumnModel().getColumn(1).setHeaderValue("Date");
            attdTable.getColumnModel().getColumn(2).setHeaderValue("Clockin");
            attdTable.getColumnModel().getColumn(3).setHeaderValue("Clockout");
            attdTable.getColumnModel().getColumn(4).setHeaderValue("lunch_clockout");
            attdTable.getColumnModel().getColumn(5).setHeaderValue("lunch_clockin");
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(619, Short.MAX_VALUE)
                .addComponent(btnLogout))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateTable() {
        //for (int count = 1; count <= 10; count++) {
            DefaultTableModel DTM = new DefaultTableModel();
            DTM.addColumn("ID");
            DTM.addColumn("Date");
            DTM.addColumn("ClockIn");
            DTM.addColumn("Clockout");
            DTM.addColumn("lunch_out");
            DTM.addColumn("lunch_in");

            for (int a = 1; a <= attdList.getNumberOfEntries(); a++) {
                DTM.addRow(new Object[]{
                    attdList.getEntry(a).getAttendance_id(),
                    attdList.getEntry(a).getDate(),
                    attdList.getEntry(a).getTime_checkin(),
                    attdList.getEntry(a).getTime_checkout(),
                    attdList.getEntry(a).getLunch_checkout(),
                    attdList.getEntry(a).getLunch_checkin()
                });
            }
            //DTM.addRow(row);
            attdTable.setModel(DTM);
        //}

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employeeInt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employeeInt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employeeInt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employeeInt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employeeInt().setVisible(true);
            }
        });
    }

    public void PreviousFrame(MainForm mainform) {
        this.mainform = mainform;
    }

    public void updateList(ListInterface<employee> empList, ListInterface<Attendance> attdList) {
        this.empList = empList;
        this.attdList = attdList;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable attdTable;
    private javax.swing.JButton btnLogout;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
